# nginx-proxy to nginx, to rapidpro
version: "3"
services:
  nginx:
    image: nginx
    links:
      - rapidpro
      - courier
    volumes:
      - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
      - "./nginx/certs:/etc/nginx/certs"
    environment:
      - VIRTUAL_HOST=${RAPIDPRO_HOST:-localhost}
      - LETSENCRYPT_HOST=${RAPIDPRO_HOST:-localhost}
      - LETSENCRYPT_EMAIL=${RAPIDPRO_ADMIN_EMAIL:-admin@example.com}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST:-true}
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST:-true}
  rapidpro:
    image: rapidpro/rapidpro:v4
    depends_on:
      - redis
      - postgresql
      - elasticsearch
    environment:
      - DOMAIN_NAME=${RAPIDPRO_HOST:-localhost}
      - ALLOWED_HOSTS=${RAPIDPRO_HOST:-localhost}
      - TEMBA_HOST=${RAPIDPRO_HOST:-localhost}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-off}
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elastic:changeme@elasticsearch:9200
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - MANAGEPY_COLLECTSTATIC=${MANAGEPY_COLLECTSTATIC:-off}
      - MANAGEPY_COMPRESS=${MANAGEPY_COMPRESS:-off}
      - MANAGEPY_INIT_DB=${MANAGEPY_INIT_DB:-on}
      - MANAGEPY_MIGRATE=${MANAGEPY_MIGRATE:-on}
      - MANAGEPY_IMPORT_GEOJSON={$MANAGEPY_IMPORT_GEOJSON:-off}
      - OSM_RELATION_IDS={$OSM_RELATION_IDS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-changeme}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-changeme}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME:-changeme}
      - AWS_BUCKET_DOMAIN=${AWS_BUCKET_DOMAIN-:changeme}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:-changeme}
      - AWS_STATIC=${AWS_STATIC:-off}
      - AWS_MEDIA=${AWS_MEDIA:-off}
      - AWS_QUERYSTRING_AUTH=${AWS_QUERYSTRIGN_AUTH:-False}
      - CDN_DOMAIN_NAME=${AWS_BUCKET_DOMAIN:-changeme}
      - EMAIL_HOST=${EMAIL_HOST:-example.com}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:-admin@example.com}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-changeme}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-admin@example.com}
      - SEND_EMAILS=${SEND_EMAILS:-off}
      - SEND_MESSAGES=${SEND_MESSAGES:-off}
      - SEND_AIRTIME=${SEND_AIRTIME:-off}
      - SEND_CALLS=${SEND_CALLS:-off}
      - SEND_WEBHOOKS=${SEND_WEBHOOKS:-off}
      - DJANGO_COMPRESSOR=${DJANGO_COMPRESSOR:-off}
      - BRANDING_ALLOW_SIGNUPS=${BRANDING_ALLOW_SIGNUPS:-on}
      - BRANDING_API_LINK=${BRANDING_API_LINK}
      - BRANDING_LINK=${BRANDING_LINK}
      - RAVEN_DSN={$RAVEN_DSN}
      - IS_PROD=${IS_PROD:-off}
  celery_base:
    image: rapidpro/rapidpro:v4
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elastic:changeme@elasticsearch:9200
      - RAVEN_DSN={$RAVEN_DSN}
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - SEND_EMAILS=${SEND_EMAILS:-off}
      - SEND_MESSAGES=${SEND_MESSAGES:-off}
      - SEND_AIRTIME=${SEND_AIRTIME:-off}
      - SEND_CALLS=${SEND_CALLS:-off}
      - SEND_WEBHOOKS=${SEND_WEBHOOKS:-off}
    command: ["/venv/bin/celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery,flows"]
  celery_msgs:
    image: rapidpro/rapidpro:v4
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elastic:changeme@elasticsearch:9200
      - RAVEN_DSN={$RAVEN_DSN}
      - SECRET_KEY=${SECRET_KEY:-changeme}
      - SEND_EMAILS=${SEND_EMAILS:-off}
      - SEND_MESSAGES=${SEND_MESSAGES:-off}
      - SEND_AIRTIME=${SEND_AIRTIME:-off}
      - SEND_CALLS=${SEND_CALLS:-off}
      - SEND_WEBHOOKS=${SEND_WEBHOOKS:-off}
    command: ["/venv/bin/celery", "--app=temba", "worker", "--loglevel=INFO", "--queues=msgs,handler"]
  redis:
    image: redis:alpine
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=rapidpro
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
  rp-indexer:
    image: praekeltfoundation/rp-indexer
    depends_on:
     - rapidpro
    links:
      - postgresql
      - elasticsearch
    environment:
      - INDEXER_DB=postgresql://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - INDEXER_ELASTIC_URL=http://elastic:changeme@elasticsearch:9200
  courier:
    image: praekeltfoundation/courier
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
    environment:
      - COURIER_DOMAIN=${RAPIDPRO_HOST:-locahost}
      - COURIER_SPOOL_DIR=/tmp/courier/
      - COURIER_DB=postgres://postgres:postgres@postgresql/rapidpro?sslmode=disable
      - COURIER_REDIS=redis://redis:6379/8
      - COURIER_SENTRY_DSN={$RAVEN_DSN}
