version: "2"
services:
  nginx:
    image: nginx
    links:
      - rapidpro
      - courier
    volumes:
      - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
    environment:
      - VIRTUAL_HOST=${RAPIDPRO_HOST}
      - VIRTUAL_NETWORK=rapidpro
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${RAPIDPRO_HOST}
      - LETSENCRYPT_EMAIL=${RAPIDPRO_ADMIN_EMAIL}
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
  rapidpro:
    image: rapidpro/rapidpro:v4
    depends_on:
      - redis
      - postgresql
      - elasticsearch
    ports:
      - "8000"
    environment:
      - DOMAIN_NAME=${RAPIDPRO_HOST}
      - ALLOWED_HOSTS=${RAPIDPRO_HOST}
      - TEMBA_HOST=${RAPIDPRO_HOST}
      - DJANGO_DEBUG=off
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SECRET_KEY=${SECRET_KEY}
      - MANAGEPY_COLLECTSTATIC=${MANAGEPY_COLLECTSTATIC}
      - MANAGEPY_COMPRESS=${MANAGEPY_COMPRESS}
      - MANAGEPY_INIT_DB=${MANAGEPY_INIT_DB}
      - MANAGEPY_MIGRATE=${MANAGEPY_MIGRATE}
      - VIRTUAL_HOST=${RAPIDPRO_HOST}
      - VIRTUAL_NETWORK=${RAPIDPRO_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${RAPIDPRO_HOST}
      - LETSENCRYPT_EMAIL=${RAPIDPRO_ADMIN_EMAIL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - AWS_BUCKET_DOMAIN=${AWS_BUCKET_DOMAIN}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_STATIC=${AWS_STATIC}
      - AWS_MEDIA=${AWS_MEDIA}
      - AWS_QUERYSTRING_AUTH=False
      - CDN_DOMAIN_NAME=${AWS_BUCKET_DOMAIN}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - SEND_EMAILS=${SEND_EMAILS}
      - SEND_MESSAGES=${SEND_MESSAGES}
      - SEND_AIRTIME=${SEND_AIRTIME}
      - SEND_CALLS=${SEND_CALLS}
      - SEND_WEBHOOKS=${SEND_WEBHOOKS}
      - DJANGO_COMPRESSOR=${DJANGO_COMPRESSOR}
      - BRANDING_ALLOW_SIGNUPS=${BRANDING_ALLOW_SIGNUPS}
      - BRANDING_API_LINK=${BRANDING_API_LINK}
      - BRANDING_LINK=${BRANDING_LINK}
      - IS_PROD=${IS_PROD}
  celery_base:
    image: rapidpro/rapidpro:v4
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SECRET_KEY=${SECRET_KEY}
    command: ["/venv/bin/celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery,flows"]
  celery_msgs:
    image: rapidpro/rapidpro:v4
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SECRET_KEY=${SECRET_KEY}
    command: ["/venv/bin/celery", "--app=temba", "worker", "--loglevel=INFO", "--queues=msgs,handler"]
  redis:
    image: redis:alpine
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=rapidpro
    volumes:
      - data:/var/lib/postgresql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  rp-indexer:
    image: praekeltfoundation/rp-indexer
    depends_on:
     - rapidpro
    links:
      - postgresql
      - elasticsearch
    environment:
      - INDEXER_DB=postgresql://postgres:postgres@postgresql/rapidpro
      - INDEXER_ELASTIC_URL=http://elasticsearch:9200
  courier:
    image: praekeltfoundation/courier
    ports:
      - "8080"
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
    environment:
      - COURIER_DOMAIN=${RAPIDPRO_HOST}
      - COURIER_SPOOL_DIR=/tmp/courier/
      - COURIER_DB=postgres://postgres:postgres@postgresql/rapidpro
      - COURIER_REDIS=redis://redis:6379/8
volumes:
  data:
    driver: local
  esdata1:
    driver: local
