version: "2"
services:
  nginx:
    image: nginx
    links:
      - rapidpro
      - courier
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./etc/nginx/conf.d/:/etc/nginx/conf.d/"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
    environment:
      - VIRTUAL_HOST=EXAMPLE.COM
      - VIRTUAL_NETWORK=EXAMPLE.COM
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=EXAMPLE.COM
      - LETSENCRYPT_EMAIL=email@example.com
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  rapidpro:
    image: sdehaan/rapidpro:v4
    depends_on:
      - redis
      - postgresql
      - elasticsearch
    ports:
      - '8000'
    environment:
      - DOMAIN_NAME=localhost
      - ALLOWED_HOSTS=localhost
      - TEMBA_HOST=localhost
      - DJANGO_DEBUG=off
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SECRET_KEY=super-secret-key
      - MANAGEPY_COLLECTSTATIC=on
      - MANAGEPY_COMPRESS=on
      - MANAGEPY_INIT_DB=on
      - MANAGEPY_MIGRATE=on
      - VIRTUAL_HOST=EXAMPLE.COM
      - VIRTUAL_NETWORK=EXAMPLE.COM
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=EXAMPLE.COM
      - LETSENCRYPT_EMAIL=email@example.com
      - AWS_ACCESS_KEY_ID=changeme
      - AWS_SECRET_ACCESS_KEY=changeme
      - AWS_S3_REGION_NAME=changeme
      - AWS_BUCKET_DOMAIN=changeme
      - AWS_STORAGE_BUCKET_NAME=changme
      - AWS_STATIC=False
      - AWS_MEDIA=False
      - AWS_QUERYSTRING_AUTH=False
      - EMAIL_HOST=smtp.example.com
      - EMAIL_HOST_USER=admin@example.com
      - EMAIL_HOST_PASSWORD=changeme
      - DEFAULT_FROM_EMAIL=admin@example.com
      - SEND_EMAILS=off
      - SEND_MESSAGES=off
      - SEND_AIRTIME=off
      - SEND_CALLS=off
      - SEND_WEBHOOKS=off
      - DJANGO_COMPRESSOR=on
      - IS_PROD=off

  celery_base:
    image: sdehaan/rapidpro:v4
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SECRET_KEY=super-secret-key
    command: ["/venv/bin/celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery,flows"]
  celery_msgs:
    image: sdehaan/rapidpro:v4
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresql/rapidpro
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SECRET_KEY=super-secret-key
    command: ["/venv/bin/celery", "--app=temba", "worker", "--loglevel=INFO", "--queues=msgs,handler"]
  redis:
    image: redis:alpine
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=rapidpro
    volumes:
      - data:/var/lib/postgresql
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  rp-indexer:
    image: praekeltfoundation/rp-indexer
    depends_on:
     - rapidpro
    links:
      - postgresql
      - elasticsearch
    environment:
      - INDEXER_DB=postgresql://postgres:postgres@postgresql/rapidpro
      - INDEXER_ELASTIC_URL=http://elasticsearch:9200
  courier:
   image: praekeltfoundation/courier
   ports:
      - "8080"
   depends_on:
     - rapidpro
   links:
     - redis
     - postgresql
   environment:
     - COURIER_DOMAIN=localhost
     - COURIER_SPOOL_DIR=/tmp/courier/
     - COURIER_DB=postgres://postgres:postgres@postgresql/rapidpro
     - COURIER_REDIS=redis://redis:6379/8
volumes:
  data:
    driver: local
  esdata1:
    driver: local
